package com.google.android.gms.fitness;

public class FitnessActivities {
    public static final String AEROBICS = "aerobics";
    public static final String BADMINTON = "badminton";
    public static final String BASEBALL = "baseball";
    public static final String BASKETBALL = "basketball";
    public static final String BIATHLON = "biathlon";
    public static final String BIKING = "biking";
    public static final String BIKING_HAND = "biking.hand";
    public static final String BIKING_MOUNTAIN = "biking.mountain";
    public static final String BIKING_ROAD = "biking.road";
    public static final String BIKING_SPINNING = "biking.spinning";
    public static final String BIKING_STATIONARY = "biking.stationary";
    public static final String BIKING_UTILITY = "biking.utility";
    public static final String BOXING = "boxing";
    public static final String CALISTHENICS = "calisthenics";
    public static final String CIRCUIT_TRAINING = "circuit_training";
    public static final String CRICKET = "cricket";
    public static final String CROSSFIT = "crossfit";
    public static final String CURLING = "curling";
    public static final String DANCING = "dancing";
    public static final String DIVING = "diving";
    public static final String ELLIPTICAL = "elliptical";
    public static final String ERGOMETER = "ergometer";
    public static final String EXTRA_STATUS = "actionStatus";
    public static final String FENCING = "fencing";
    public static final String FOOTBALL_AMERICAN = "football.american";
    public static final String FOOTBALL_AUSTRALIAN = "football.australian";
    public static final String FOOTBALL_SOCCER = "football.soccer";
    public static final String FRISBEE_DISC = "frisbee_disc";
    public static final String GARDENING = "gardening";
    public static final String GOLF = "golf";
    public static final String GYMNASTICS = "gymnastics";
    public static final String HANDBALL = "handball";
    public static final String HIGH_INTENSITY_INTERVAL_TRAINING = "interval_training.high_intensity";
    public static final String HIKING = "hiking";
    public static final String HOCKEY = "hockey";
    public static final String HORSEBACK_RIDING = "horseback_riding";
    public static final String HOUSEWORK = "housework";
    public static final String ICE_SKATING = "ice_skating";
    public static final String INTERVAL_TRAINING = "interval_training";
    public static final String IN_VEHICLE = "in_vehicle";
    public static final String JUMP_ROPE = "jump_rope";
    public static final String KAYAKING = "kayaking";
    public static final String KETTLEBELL_TRAINING = "kettlebell_training";
    public static final String KICKBOXING = "kickboxing";
    public static final String KICK_SCOOTER = "kick_scooter";
    public static final String KITESURFING = "kitesurfing";
    public static final String MARTIAL_ARTS = "martial_arts";
    public static final String MEDITATION = "meditation";
    public static final String MIME_TYPE_PREFIX = "vnd.google.fitness.activity/";
    public static final String MIXED_MARTIAL_ARTS = "martial_arts.mixed";
    public static final String ON_FOOT = "on_foot";
    public static final String OTHER = "other";
    public static final String P90X = "p90x";
    public static final String PARAGLIDING = "paragliding";
    public static final String PILATES = "pilates";
    public static final String POLO = "polo";
    public static final String RACQUETBALL = "racquetball";
    public static final String ROCK_CLIMBING = "rock_climbing";
    public static final String ROWING = "rowing";
    public static final String ROWING_MACHINE = "rowing.machine";
    public static final String RUGBY = "rugby";
    public static final String RUNNING = "running";
    public static final String RUNNING_JOGGING = "running.jogging";
    public static final String RUNNING_SAND = "running.sand";
    public static final String RUNNING_TREADMILL = "running.treadmill";
    public static final String SAILING = "sailing";
    public static final String SCUBA_DIVING = "scuba_diving";
    public static final String SKATEBOARDING = "skateboarding";
    public static final String SKATING = "skating";
    public static final String SKATING_CROSS = "skating.cross";
    public static final String SKATING_INDOOR = "skating.indoor";
    public static final String SKATING_INLINE = "skating.inline";
    public static final String SKIING = "skiing";
    public static final String SKIING_BACK_COUNTRY = "skiing.back_country";
    public static final String SKIING_CROSS_COUNTRY = "skiing.cross_country";
    public static final String SKIING_DOWNHILL = "skiing.downhill";
    public static final String SKIING_KITE = "skiing.kite";
    public static final String SKIING_ROLLER = "skiing.roller";
    public static final String SLEDDING = "sledding";
    public static final String SLEEP = "sleep";
    public static final String SLEEP_AWAKE = "sleep.awake";
    public static final String SLEEP_DEEP = "sleep.deep";
    public static final String SLEEP_LIGHT = "sleep.light";
    public static final String SLEEP_REM = "sleep.rem";
    public static final String SNOWBOARDING = "snowboarding";
    public static final String SNOWMOBILE = "snowmobile";
    public static final String SNOWSHOEING = "snowshoeing";
    public static final String SQUASH = "squash";
    public static final String STAIR_CLIMBING = "stair_climbing";
    public static final String STAIR_CLIMBING_MACHINE = "stair_climbing.machine";
    public static final String STANDUP_PADDLEBOARDING = "standup_paddleboarding";
    public static final String STATUS_ACTIVE = "ActiveActionStatus";
    public static final String STATUS_COMPLETED = "CompletedActionStatus";
    public static final String STILL = "still";
    public static final String STRENGTH_TRAINING = "strength_training";
    public static final String SURFING = "surfing";
    public static final String SWIMMING = "swimming";
    public static final String SWIMMING_OPEN_WATER = "swimming.open_water";
    public static final String SWIMMING_POOL = "swimming.pool";
    public static final String TABLE_TENNIS = "table_tennis";
    public static final String TEAM_SPORTS = "team_sports";
    public static final String TENNIS = "tennis";
    public static final String TILTING = "tilting";
    public static final String TREADMILL = "treadmill";
    public static final String UNKNOWN = "unknown";
    public static final String VOLLEYBALL = "volleyball";
    public static final String VOLLEYBALL_BEACH = "volleyball.beach";
    public static final String VOLLEYBALL_INDOOR = "volleyball.indoor";
    public static final String WAKEBOARDING = "wakeboarding";
    public static final String WALKING = "walking";
    public static final String WALKING_FITNESS = "walking.fitness";
    public static final String WALKING_NORDIC = "walking.nordic";
    public static final String WALKING_STROLLER = "walking.stroller";
    public static final String WALKING_TREADMILL = "walking.treadmill";
    public static final String WATER_POLO = "water_polo";
    public static final String WEIGHTLIFTING = "weightlifting";
    public static final String WHEELCHAIR = "wheelchair";
    public static final String WINDSURFING = "windsurfing";
    public static final String YOGA = "yoga";
    public static final String ZUMBA = "zumba";
    private static final String[] zzajE;

    static {
        FitnessActivities.zzajE = new String[0x75];
        FitnessActivities.zzajE[9] = "aerobics";
        FitnessActivities.zzajE[10] = "badminton";
        FitnessActivities.zzajE[11] = "baseball";
        FitnessActivities.zzajE[12] = "basketball";
        FitnessActivities.zzajE[13] = "biathlon";
        FitnessActivities.zzajE[1] = "biking";
        FitnessActivities.zzajE[14] = "biking.hand";
        FitnessActivities.zzajE[15] = "biking.mountain";
        FitnessActivities.zzajE[16] = "biking.road";
        FitnessActivities.zzajE[17] = "biking.spinning";
        FitnessActivities.zzajE[18] = "biking.stationary";
        FitnessActivities.zzajE[19] = "biking.utility";
        FitnessActivities.zzajE[20] = "boxing";
        FitnessActivities.zzajE[21] = "calisthenics";
        FitnessActivities.zzajE[22] = "circuit_training";
        FitnessActivities.zzajE[23] = "cricket";
        FitnessActivities.zzajE[0x71] = "crossfit";
        FitnessActivities.zzajE[106] = "curling";
        FitnessActivities.zzajE[24] = "dancing";
        FitnessActivities.zzajE[102] = "diving";
        FitnessActivities.zzajE[25] = "elliptical";
        FitnessActivities.zzajE[103] = "ergometer";
        FitnessActivities.zzajE[6] = "exiting_vehicle";
        FitnessActivities.zzajE[26] = "fencing";
        FitnessActivities.zzajE[27] = "football.american";
        FitnessActivities.zzajE[28] = "football.australian";
        FitnessActivities.zzajE[29] = "football.soccer";
        FitnessActivities.zzajE[30] = "frisbee_disc";
        FitnessActivities.zzajE[0x1F] = "gardening";
        FitnessActivities.zzajE[0x20] = "golf";
        FitnessActivities.zzajE[33] = "gymnastics";
        FitnessActivities.zzajE[34] = "handball";
        FitnessActivities.zzajE[0x72] = "interval_training.high_intensity";
        FitnessActivities.zzajE[35] = "hiking";
        FitnessActivities.zzajE[36] = "hockey";
        FitnessActivities.zzajE[37] = "horseback_riding";
        FitnessActivities.zzajE[38] = "housework";
        FitnessActivities.zzajE[104] = "ice_skating";
        FitnessActivities.zzajE[0] = "in_vehicle";
        FitnessActivities.zzajE[0x73] = "interval_training";
        FitnessActivities.zzajE[39] = "jump_rope";
        FitnessActivities.zzajE[40] = "kayaking";
        FitnessActivities.zzajE[41] = "kettlebell_training";
        FitnessActivities.zzajE[107] = "kick_scooter";
        FitnessActivities.zzajE[42] = "kickboxing";
        FitnessActivities.zzajE[43] = "kitesurfing";
        FitnessActivities.zzajE[44] = "martial_arts";
        FitnessActivities.zzajE[45] = "meditation";
        FitnessActivities.zzajE[46] = "martial_arts.mixed";
        FitnessActivities.zzajE[2] = "on_foot";
        FitnessActivities.zzajE[108] = "other";
        FitnessActivities.zzajE[0x2F] = "p90x";
        FitnessActivities.zzajE[0x30] = "paragliding";
        FitnessActivities.zzajE[49] = "pilates";
        FitnessActivities.zzajE[50] = "polo";
        FitnessActivities.zzajE[51] = "racquetball";
        FitnessActivities.zzajE[52] = "rock_climbing";
        FitnessActivities.zzajE[53] = "rowing";
        FitnessActivities.zzajE[54] = "rowing.machine";
        FitnessActivities.zzajE[55] = "rugby";
        FitnessActivities.zzajE[8] = "running";
        FitnessActivities.zzajE[56] = "running.jogging";
        FitnessActivities.zzajE[57] = "running.sand";
        FitnessActivities.zzajE[58] = "running.treadmill";
        FitnessActivities.zzajE[59] = "sailing";
        FitnessActivities.zzajE[60] = "scuba_diving";
        FitnessActivities.zzajE[61] = "skateboarding";
        FitnessActivities.zzajE[62] = "skating";
        FitnessActivities.zzajE[0x3F] = "skating.cross";
        FitnessActivities.zzajE[105] = "skating.indoor";
        FitnessActivities.zzajE[0x40] = "skating.inline";
        FitnessActivities.zzajE[65] = "skiing";
        FitnessActivities.zzajE[66] = "skiing.back_country";
        FitnessActivities.zzajE[67] = "skiing.cross_country";
        FitnessActivities.zzajE[68] = "skiing.downhill";
        FitnessActivities.zzajE[69] = "skiing.kite";
        FitnessActivities.zzajE[70] = "skiing.roller";
        FitnessActivities.zzajE[71] = "sledding";
        FitnessActivities.zzajE[72] = "sleep";
        FitnessActivities.zzajE[109] = "sleep.light";
        FitnessActivities.zzajE[110] = "sleep.deep";
        FitnessActivities.zzajE[0x6F] = "sleep.rem";
        FitnessActivities.zzajE[0x70] = "sleep.awake";
        FitnessActivities.zzajE[73] = "snowboarding";
        FitnessActivities.zzajE[74] = "snowmobile";
        FitnessActivities.zzajE[75] = "snowshoeing";
        FitnessActivities.zzajE[76] = "squash";
        FitnessActivities.zzajE[77] = "stair_climbing";
        FitnessActivities.zzajE[78] = "stair_climbing.machine";
        FitnessActivities.zzajE[0x4F] = "standup_paddleboarding";
        FitnessActivities.zzajE[3] = "still";
        FitnessActivities.zzajE[80] = "strength_training";
        FitnessActivities.zzajE[81] = "surfing";
        FitnessActivities.zzajE[82] = "swimming";
        FitnessActivities.zzajE[83] = "swimming.pool";
        FitnessActivities.zzajE[84] = "swimming.open_water";
        FitnessActivities.zzajE[85] = "table_tennis";
        FitnessActivities.zzajE[86] = "team_sports";
        FitnessActivities.zzajE[87] = "tennis";
        FitnessActivities.zzajE[5] = "tilting";
        FitnessActivities.zzajE[88] = "treadmill";
        FitnessActivities.zzajE[4] = "unknown";
        FitnessActivities.zzajE[89] = "volleyball";
        FitnessActivities.zzajE[90] = "volleyball.beach";
        FitnessActivities.zzajE[91] = "volleyball.indoor";
        FitnessActivities.zzajE[92] = "wakeboarding";
        FitnessActivities.zzajE[7] = "walking";
        FitnessActivities.zzajE[93] = "walking.fitness";
        FitnessActivities.zzajE[94] = "walking.nordic";
        FitnessActivities.zzajE[0x5F] = "walking.treadmill";
        FitnessActivities.zzajE[0x74] = "walking.stroller";
        FitnessActivities.zzajE[0x60] = "water_polo";
        FitnessActivities.zzajE[97] = "weightlifting";
        FitnessActivities.zzajE[98] = "wheelchair";
        FitnessActivities.zzajE[99] = "windsurfing";
        FitnessActivities.zzajE[100] = "yoga";
        FitnessActivities.zzajE[101] = "zumba";
    }

    public static String getMimeType(String activity) {
        return "vnd.google.fitness.activity/" + activity;
    }

    public static String getName(int activity) {
        if(activity < 0 || activity >= FitnessActivities.zzajE.length) {
            return "unknown";
        }
        String s = FitnessActivities.zzajE[activity];
        return s == null ? "unknown" : s;
    }

    public static int zzcF(String s) {
        for(int v = 0; v < FitnessActivities.zzajE.length; ++v) {
            if(FitnessActivities.zzajE[v].equals(s)) {
                return v;
            }
        }
        return 4;
    }
}

